// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogDocumentDataSlicesSlice = BlogSlice | BannerSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;

type FeatureDocumentDataSlicesSlice = FeatureHeroSlice;

/**
 * Content for Feature documents
 */
interface FeatureDocumentData {
  /**
   * Slice Zone field in *Feature*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FeatureDocumentDataSlicesSlice> /**
   * Meta Title field in *Feature*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: feature.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Feature*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: feature.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Feature*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Feature document from Prismic
 *
 * - **API ID**: `feature`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeatureDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FeatureDocumentData>,
    "feature",
    Lang
  >;

type LandingDocumentDataSlicesSlice =
  | OffersSlice
  | FeaturedProductsSlice
  | HeroSlice;

/**
 * Content for Landing documents
 */
interface LandingDocumentData {
  /**
   * Slice Zone field in *Landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingDocumentData>,
    "landing",
    Lang
  >;

export type AllDocumentTypes = BlogDocument | FeatureDocument | LandingDocument;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Background field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background: prismic.ImageField<never>;

  /**
   * Heading field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * First  field in *Banner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.home
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  home: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Second field in *Banner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.second
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  second: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bottom Image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.bottom_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bottom_image: prismic.ImageField<never>;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Item in *Blog → Default → Primary → Blogs*
 */
export interface BlogSliceDefaultPrimaryBlogsItem {
  /**
   * Blog Cover field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].blog_cover
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  blog_cover: prismic.ImageField<never>;

  /**
   * Category field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Blog Title field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].blog_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blog_title: prismic.KeyTextField;

  /**
   * Views field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].viewa
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  viewa: prismic.KeyTextField;

  /**
   * Comments field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].comments
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  comments: prismic.KeyTextField;

  /**
   * Date field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Description field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Author Image field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].author_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Author Name field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Read More field in *Blog → Default → Primary → Blogs*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[].read_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  read_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Blog → Default → Primary*
 */
export interface BlogSliceDefaultPrimary {
  /**
   * Blogs field in *Blog → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blogs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blogs: prismic.GroupField<Simplify<BlogSliceDefaultPrimaryBlogsItem>>;
}

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;

/**
 * Primary content in *FeatureHero → Default → Primary*
 */
export interface FeatureHeroSliceDefaultPrimary {
  /**
   * Tagline field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Heading field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Button field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Green Background field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.green_background
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  green_background: prismic.ImageField<never>;

  /**
   * Product Image field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.product_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Leaves 1 field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.leaves_1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  leaves_1: prismic.ImageField<never>;

  /**
   * Leaves 2 field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.leaves_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  leaves_2: prismic.ImageField<never>;

  /**
   * Ingredient 1 field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.ingredient_1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ingredient_1: prismic.ImageField<never>;

  /**
   * Ingredient 2 field in *FeatureHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_hero.default.primary.ingredient_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ingredient_2: prismic.ImageField<never>;
}

/**
 * Default variation for FeatureHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureHero*
 */
type FeatureHeroSliceVariation = FeatureHeroSliceDefault;

/**
 * FeatureHero Shared Slice
 *
 * - **API ID**: `feature_hero`
 * - **Description**: FeatureHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureHeroSlice = prismic.SharedSlice<
  "feature_hero",
  FeatureHeroSliceVariation
>;

/**
 * Item in *FeaturedProducts → Default → Primary → Product Card*
 */
export interface FeaturedProductsSliceDefaultPrimaryProductCardItem {
  /**
   * Chip field in *FeaturedProducts → Default → Primary → Product Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.product_card[].chip
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  chip: prismic.KeyTextField;

  /**
   * Product Image field in *FeaturedProducts → Default → Primary → Product Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.product_card[].product_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Category field in *FeaturedProducts → Default → Primary → Product Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.product_card[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Name field in *FeaturedProducts → Default → Primary → Product Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.product_card[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Old Price field in *FeaturedProducts → Default → Primary → Product Card*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.product_card[].old_price
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  old_price: prismic.NumberField;

  /**
   * New Price field in *FeaturedProducts → Default → Primary → Product Card*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.product_card[].new_price
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  new_price: prismic.NumberField;

  /**
   * Product Detail Link field in *FeaturedProducts → Default → Primary → Product Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.product_card[].product_detail_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  product_detail_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *FeaturedProducts → Default → Primary*
 */
export interface FeaturedProductsSliceDefaultPrimary {
  /**
   * Features Tagline field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.features_tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  features_tagline: prismic.KeyTextField;

  /**
   * Features Product Heading field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.features_product_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  features_product_heading: prismic.KeyTextField;

  /**
   * Product Card field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.product_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  product_card: prismic.GroupField<
    Simplify<FeaturedProductsSliceDefaultPrimaryProductCardItem>
  >;
}

/**
 * Default variation for FeaturedProducts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedProducts*
 */
type FeaturedProductsSliceVariation = FeaturedProductsSliceDefault;

/**
 * FeaturedProducts Shared Slice
 *
 * - **API ID**: `featured_products`
 * - **Description**: FeaturedProducts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProductsSlice = prismic.SharedSlice<
  "featured_products",
  FeaturedProductsSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Hero Cards*
 */
export interface HeroSliceDefaultPrimaryHeroCardsItem {
  /**
   * Icon field in *Hero → Default → Primary → Hero Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Default → Primary → Hero Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_cards[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *Hero → Default → Primary → Hero Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_cards[].sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Learn More field in *Hero → Default → Primary → Hero Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_cards[].learn_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  learn_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Bottom Shaper field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bottom_shaper
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bottom_shaper: prismic.ImageField<never>;

  /**
   * Background field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background: prismic.ImageField<never>;

  /**
   * Clouds field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.clouds
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  clouds: prismic.ImageField<never>;

  /**
   * Tagline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Product Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.product_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Hero Cards field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  hero_cards: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryHeroCardsItem>
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Offers → Default → Primary → Offer Card*
 */
export interface OffersSliceDefaultPrimaryOfferCardItem {
  /**
   * Offer Exclusivity field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].offer_exclusivity
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  offer_exclusivity: prismic.KeyTextField;

  /**
   * Bottle Units field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].bottle_units
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bottle_units: prismic.KeyTextField;

  /**
   * Name field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Bottle Caps field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].bottle_caps
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bottle_caps: prismic.KeyTextField;

  /**
   * Product Image field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].product_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Price field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].price
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Total Price field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].total_price
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  total_price: prismic.NumberField;

  /**
   * Save field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].save
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  save: prismic.KeyTextField;

  /**
   * Free Shipping field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].free_shipping
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  free_shipping: prismic.KeyTextField;

  /**
   * Buy Now Button field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].buy_now_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buy_now_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Brand Logos field in *Offers → Default → Primary → Offer Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[].brand_logos
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  brand_logos: prismic.ImageField<never>;
}

/**
 * Primary content in *Offers → Default → Primary*
 */
export interface OffersSliceDefaultPrimary {
  /**
   * Tagline field in *Offers → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Offers Heading field in *Offers → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offers_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  offers_heading: prismic.KeyTextField;

  /**
   * Offer Card field in *Offers → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.default.primary.offer_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  offer_card: prismic.GroupField<
    Simplify<OffersSliceDefaultPrimaryOfferCardItem>
  >;
}

/**
 * Default variation for Offers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OffersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OffersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Offers*
 */
type OffersSliceVariation = OffersSliceDefault;

/**
 * Offers Shared Slice
 *
 * - **API ID**: `offers`
 * - **Description**: Offers
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OffersSlice = prismic.SharedSlice<"offers", OffersSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      FeatureDocument,
      FeatureDocumentData,
      FeatureDocumentDataSlicesSlice,
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BlogSlice,
      BlogSliceDefaultPrimaryBlogsItem,
      BlogSliceDefaultPrimary,
      BlogSliceVariation,
      BlogSliceDefault,
      FeatureHeroSlice,
      FeatureHeroSliceDefaultPrimary,
      FeatureHeroSliceVariation,
      FeatureHeroSliceDefault,
      FeaturedProductsSlice,
      FeaturedProductsSliceDefaultPrimaryProductCardItem,
      FeaturedProductsSliceDefaultPrimary,
      FeaturedProductsSliceVariation,
      FeaturedProductsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryHeroCardsItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      OffersSlice,
      OffersSliceDefaultPrimaryOfferCardItem,
      OffersSliceDefaultPrimary,
      OffersSliceVariation,
      OffersSliceDefault,
    };
  }
}
