// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  blog: dynamic(() => import("./Blog")),
  feature_hero: dynamic(() => import("./FeatureHero")),
  featured_products: dynamic(() => import("./FeaturedProducts")),
  hero: dynamic(() => import("./Hero")),
  offers: dynamic(() => import("./Offers")),
};
